#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
if(length(args)!=2){
  message("\nERROR:\t2 argument required")
  message("\nUSAGE:\tRscript apply_pbem_scaling_factor_on_oncotab.R <Results_folder_abemus> <Pbem scaling factor>\n")
  cat(paste("\t[1] path\tResults folder generated by abemus","\n"))
  cat(paste("\t[2] SF  \tpbem scaling factor to apply","\n\n"))
  quit()
}

library(data.table)

# Abemus Results folder
wd = args[1]
SF = as.numeric(args[2])
ld = list.dirs(path = wd,full.names = T,recursive = F)

#x=ld[1]
for(x in ld){
  message(x)
  setwd(x)
  pmtab.file=list.files(x,full.names = T,pattern = "\\.onco\\.tsv$")
  a=read.delim(pmtab.file,as.is = T,stringsAsFactors = F)
  a$filter.pbem_coverage = a$filter.pbem_coverage * SF
  a$pass.filter.pbem_coverage = 0
  a$pass.filter.pbem_coverage[which(a$af_case >= a$filter.pbem_coverage)] = 1
  a=a[which(a$pass.filter.pbem_coverage==1),]
  # print non-synonymous snvs
  a.miss = a[which(a$Variant_Classification %in% c("Missense_Mutation","Nonsense_Mutation")),]
  out.name=gsub(basename(pmtab.file),pattern = "\\.tsv",replacement = paste0(".miss.",SF,".tsv"))
  write.table(x = a.miss,file = out.name,quote = F,sep = "\t",row.names = F,col.names = T)
  # print all snvs
  out.name=gsub(basename(pmtab.file),pattern = "\\.tsv",replacement = paste0(".",SF,".tsv"))
  write.table(x = a,file = out.name,quote = F,sep = "\t",row.names = F,col.names = T)
}
