#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
if(length(args)!=2){
  message("\nERROR:\t1 argument required")
  message("\nUSAGE:\tRscript oncotator_on_F3.R <Results_folder_abemus> <AF threshold>\n")
  cat(paste("\t[1] path\tResults folder generated by abemus","\n"))
  cat(paste("\t[2] cutoff\tAF threshold to apply","\n\n"))
  quit()
}

library(data.table)

# Abemus Results folder
wd = args[1]
AF = args[2] # 0.05 
ld = list.dirs(path = wd,full.names = T,recursive = F)

#pm=ld[1]
for(pm in ld){
  setwd(pm)
  message(pm)
  cpmf3.file = list.files(pm,pattern = "pmtab_F3_")
  cpmf3 = fread(input = cpmf3.file,header = T,sep='\t',colClasses = list(character=2))
  cpmf3 = data.frame(cpmf3,stringsAsFactors = F)
  # Keep only snvs passing the pbem filter
  cpmf3 = cpmf3[which(cpmf3$pass.filter.pbem_coverage == 1),]
  # TMP
  cpmf3 = cpmf3[which(cpmf3$af_case >= as.numeric(AF)),]
  # Annotation with Oncotator for calls only:abemus
  maflite = unique(cpmf3[c(2,3,3,4,6)])
  colnames(maflite) = c('chr','start','end','ref_allele','alt_allele')
  write.table(maflite,file = "pmtab_MAFLITE.tsv",col.names = T,sep = '\t',row.names = F,quote = F,append = F)
  # run oncotator
  system("cd $(readlink -f $PWD)")
  ONCOTATOR = 'Rscript /elaborazioni/sharedCO/Home_casiraghi/Prog/Oncotator/run_oncotator.R'
  cmd = paste(ONCOTATOR,"pmtab_MAFLITE.tsv")
  system(cmd)
  onco = read.delim(file = paste0("pmtab.oncotator.txt"),as.is = T,header = T,comment.char = "#")
  onco$group = paste(onco$Chromosome,onco$Start_position,onco$Reference_Allele,sep = ":")
  onco = onco[,c("group","Hugo_Symbol","Variant_Classification","Protein_Change")]
  cpmf3 = merge(x = cpmf3,y = onco,by = "group",all.x = T)
  cpmf3$Protein_Change[which(cpmf3$Protein_Change=="")] <- NA
  file.out = gsub(cpmf3.file,pattern = "\\.tsv$",replacement = ".onco.tsv")
  write.table(cpmf3,file = file.out,col.names = T,sep = '\t',row.names = F,quote = F,append = F)
  system("rm oncotator.log pmtab_MAFLITE.tsv pmtab.oncotator.txt")
}