## Split PaCBAM pileup and snvs outputs by chromosomes

cat(paste("\n[",Sys.time(),"]\tSplit pileup and snvs data from PaCBAM by chromosome","\n"))
library(parallel)

args <- commandArgs(trailingOnly = TRUE)
if(length(args)!=4){
  message("\nERROR:\t5 arguments required")
  message("\nUSAGE:\tRscript PaCBAM_by_chromosome.R bed bamlist pacbam ncores outdir\n")
  cat(paste("\t[1] bed\t\tTarget regions in BED format",
            "\t[2] pacbam\tFolder with outputs generated by PaCBAM",
            "\t[3] ncores\tNumber of chromosomes to split in parallel",
            "\t[4] outdir\tOutput folder in which subfolders for each sample will be created",sep="\n"),"\n\n")  
  quit()
}

targetbed = args[1]
pacbamfolder = args[2]
mc.cores = args[3]
outdir = args[4]

timestart <- proc.time()

pileup_splitbychr <- function(id,CHR,pileup_file){
  chrom = CHR[id]
  filename = gsub(basename(pileup_file),pattern = ".pileup",replacement = paste0("_chr",gsub(chrom,pattern = "chr",replacement = ""),".pileup"))
  cat(c("chr","pos","ref","A","C","G","T","af","cov","dbsnp\n"),sep = "\t",file = filename)
  awk = paste0("/usr/bin/awk '{if ($1 == \"",chrom,"\") { print $0; }}' ",pileup_file," >> ",filename)
  system(awk)
}

snvs_splitbychr <- function(id,CHR,snvs_file){
  chrom = CHR[id]
  filename = gsub(basename(snvs_file),pattern = ".snvs",replacement = paste0("_chr",gsub(chrom,pattern = "chr",replacement = ""),".snvs"))
  cat(c("chr","pos","ref","alt","A","C","G","T","af","cov","Ars","Crs","Grs","Trs","dbsnp\n"),sep = "\t",file = filename)
  awk = paste0("/usr/bin/awk '{if ($1 == \"",chrom,"\") { print $0; }}' ",snvs_file," >> ",filename)
  system(awk)
}

pacbamlist = list.files(pacbamfolder,full.names = T,pattern = "\\.snvs$|\\.pileup$")
samplelist = unique(gsub(basename(pacbamlist),pattern = '.snvs|.pileup',replacement = ''))

CHR = read.delim(targetbed,as.is = T,header = F)
CHR = sort(unique(CHR[,1]))

message("Create output folders for each sample:")
for(sname in samplelist){
  dirname <- sname
  message(dirname)
  dir.create(file.path(outdir,dirname))
  cat("Writing pileup output by chromosome \t")
  dir.create(file.path(outdir,dirname,"pileup"))
  setwd(file.path(outdir,dirname,"pileup"))
  pileup_list = grep(pacbamlist,pattern = "\\.pileup$",value = T)
  pileup_file = grep(pileup_list,pattern = dirname,value = T)
  mclapply(seq(1,length(CHR),1),pileup_splitbychr,CHR=CHR,pileup_file=pileup_file,mc.cores=mc.cores)
  cat("[ OK ]\n")
  cat("Writing snvs output by chromosome \t")
  dir.create(file.path(outdir,dirname,"snvs"))
  setwd(file.path(outdir,dirname,"snvs"))
  snvs_list = grep(pacbamlist,pattern = "\\.snvs$",value = T)
  snvs_file = grep(snvs_list,pattern = dirname,value = T)
  mclapply(seq(1,length(CHR),1),snvs_splitbychr,CHR=CHR,snvs_file=snvs_file,mc.cores=mc.cores)
  cat("[ OK ]\n")
}

proc.time()-timestart
