## Split PaCBAM pileup and snvs outputs by chromosomes

cat(paste("\n[",Sys.time(),"]\tSplit pileup and snvs data from PaCBAM by chromosome","\n"))
library(parallel)

args <- commandArgs(trailingOnly = TRUE)
if(length(args)!=9){
  message("\nERROR:\t5 arguments required")
  message("\nUSAGE:\tRscript PaCBAM_by_chromosome.R -bed -bamlist -pacbam -outdir\n")
  cat(paste("\t-bed\t\tTarget regions in BED format",
            "\t-bamlist\tList of BAM files that have PaCBAM outputs",
            "\t-pacbam\t\tFolder with outputs generated by PaCBAM",
            "\t-ncores\t\tNumber of chromosomes to split in parallel",
            "\t-outdir\t\tOutput folder in which subfolders for each sample will be created",sep="\n"),"\n\n")  
  quit()
}
args = data.frame(flag=args[c(1,3,5,7)],input=args[c(2,4,6,8)],stringsAsFactors = F)

bamlist.file <- as.character(args$input[which(args$flag=='-bamlist')])
targetbed = as.character(args$input[which(args$flag=='-bed')]) 
pacbamfolder = as.character(args$input[which(args$flag=='-pacbam')])
outdir = as.character(args$input[which(args$flag=='-outdir')])
mc.cores = as.numeric(args$input[which(args$flag=='-ncores')])

timestart <- proc.time()

pileup_splitbychr <- function(id,CHR,pileup_file){
  chrom = CHR[id]
  filename = gsub(basename(pileup_file),pattern = ".pileup",replacement = paste0("_chr",gsub(chrom,pattern = "chr",replacement = ""),".pileup"))
  cat(c("chr","pos","ref","A","C","G","T","af","cov","dbsnp\n"),sep = "\t",file = filename)
  awk = paste0("/usr/bin/awk '{if ($1 == \"",chrom,"\") { print $0; }}' ",pileup_file," >> ",filename)
  system(awk)
}

snvs_splitbychr <- function(id,CHR,snvs_file){
  chrom = CHR[id]
  filename = gsub(basename(snvs_file),pattern = ".snvs",replacement = paste0("_chr",gsub(chrom,pattern = "chr",replacement = ""),".snvs"))
  cat(c("chr","pos","ref","A","C","G","T","af","cov","Ars","Crs","Grs","Trs","dbsnp\n"),sep = "\t",file = filename)
  awk = paste0("/usr/bin/awk '{if ($1 == \"",chrom,"\") { print $0; }}' ",snvs_file," >> ",filename)
  system(awk)
}

bamlist = readLines(bamlist.file)
pacbamlist = list.files(pacbamfolder,full.names = T,pattern = "\\.snvs$|\\.pileup$")
CHR = read.delim(targetbed,as.is = T,header = F)
CHR = sort(unique(CHR[,1]))
message("Create output folders for each sample:")
for(sname in bamlist){
  dirname = gsub(basename(sname),pattern = "\\.bam$",replacement = "")
  message(dirname)
  dir.create(file.path(outdir,dirname))
  cat("Writing pileup output by chromosome \t")
  dir.create(file.path(outdir,dirname,"pileup"))
  setwd(file.path(outdir,dirname,"pileup"))
  pileup_list = grep(pacbamlist,pattern = "\\.pileup$",value = T)
  pileup_file = grep(pileup_list,pattern = dirname,value = T)
  mclapply(seq(1,length(CHR),1),pileup_splitbychr,CHR=CHR,pileup_file=pileup_file,mc.cores=mc.cores)
  cat("[ OK ]\n")
  cat("Writing snvs output by chromosome \t")
  dir.create(file.path(outdir,dirname,"snvs"))
  setwd(file.path(outdir,dirname,"snvs"))
  snvs_list = grep(pacbamlist,pattern = "\\.snvs$",value = T)
  snvs_file = grep(snvs_list,pattern = dirname,value = T)
  mclapply(seq(1,length(CHR),1),snvs_splitbychr,CHR=CHR,snvs_file=snvs_file,mc.cores=mc.cores)
  cat("[ OK ]\n")
}

proc.time()-timestart