## Split PaCBAM pileup and snvs outputs by chromosomes

cat(paste("\n[",Sys.time(),"]\tSplit pileup and snvs data from PaCBAM by chromosome","\n"))
library(parallel)

args <- commandArgs(trailingOnly = TRUE)
if(length(args)!=5){
  message("\nERROR:\t5 arguments required")
  message("\nUSAGE:\tRscript PaCBAM_by_chromosome.R bed=string bamlist=string pacbam=string outdir=string ncores=int\n")
  cat(paste("\tbed\t\tTarget regions in BED format",
            "\tbamlist\t\tList of BAM files that have PaCBAM outputs",
            "\tpacbam\t\tFolder with outputs generated by PaCBAM",
            "\tncores\t\tNumber of chromosomes to split in parallel",
            "\toutdir\t\tOutput folder in which subfolders for each sample will be created",sep="\n"),"\n\n")  
  quit()
}

bamlist.file = unlist(strsplit(grep(args,pattern = 'bamlist=',value = T),split = '='))[2]
targetbed = unlist(strsplit(grep(args,pattern = 'bed=',value = T),split = '='))[2]
pacbamfolder = unlist(strsplit(grep(args,pattern = 'pacbam=',value = T),split = '='))[2]
outdir = unlist(strsplit(grep(args,pattern = 'outdir=',value = T),split = '='))[2]
mc.cores = as.integer(unlist(strsplit(grep(args,pattern = 'ncores=',value = T),split = '='))[2])

timestart <- proc.time()

pileup_splitbychr <- function(id,CHR,pileup_file){
  chrom = CHR[id]
  filename = gsub(basename(pileup_file),pattern = ".pileup",replacement = paste0("_chr",gsub(chrom,pattern = "chr",replacement = ""),".pileup"))
  cat(c("chr","pos","ref","A","C","G","T","af","cov","dbsnp\n"),sep = "\t",file = filename)
  awk = paste0("/usr/bin/awk '{if ($1 == \"",chrom,"\") { print $0; }}' ",pileup_file," >> ",filename)
  system(awk)
}

snvs_splitbychr <- function(id,CHR,snvs_file){
  chrom = CHR[id]
  filename = gsub(basename(snvs_file),pattern = ".snvs",replacement = paste0("_chr",gsub(chrom,pattern = "chr",replacement = ""),".snvs"))
  cat(c("chr","pos","ref","A","C","G","T","af","cov","Ars","Crs","Grs","Trs","dbsnp\n"),sep = "\t",file = filename)
  awk = paste0("/usr/bin/awk '{if ($1 == \"",chrom,"\") { print $0; }}' ",snvs_file," >> ",filename)
  system(awk)
}

bamlist = readLines(bamlist.file)
pacbamlist = list.files(pacbamfolder,full.names = T,pattern = "\\.snvs$|\\.pileup$")
CHR = read.delim(targetbed,as.is = T,header = F)
CHR = sort(unique(CHR[,1]))
message("Create output folders for each sample:")
for(sname in bamlist){
  dirname = gsub(basename(sname),pattern = "\\.bam$",replacement = "")
  message(dirname)
  dir.create(file.path(outdir,dirname))
  cat("Writing pileup output by chromosome \t")
  dir.create(file.path(outdir,dirname,"pileup"))
  setwd(file.path(outdir,dirname,"pileup"))
  pileup_list = grep(pacbamlist,pattern = "\\.pileup$",value = T)
  pileup_file = grep(pileup_list,pattern = dirname,value = T)
  mclapply(seq(1,length(CHR),1),pileup_splitbychr,CHR=CHR,pileup_file=pileup_file,mc.cores=mc.cores)
  cat("[ OK ]\n")
  cat("Writing snvs output by chromosome \t")
  dir.create(file.path(outdir,dirname,"snvs"))
  setwd(file.path(outdir,dirname,"snvs"))
  snvs_list = grep(pacbamlist,pattern = "\\.snvs$",value = T)
  snvs_file = grep(snvs_list,pattern = dirname,value = T)
  mclapply(seq(1,length(CHR),1),snvs_splitbychr,CHR=CHR,snvs_file=snvs_file,mc.cores=mc.cores)
  cat("[ OK ]\n")
}

proc.time()-timestart
